### ISSUE TITLE
version 1.1.0 got error in node 8.12.0

### ISSUE THREAD

**Issue by mosquito1803** [lazd/gulp-replace#112]
We are using gulp-replace in node 8.12.0, verison 1.0.0 goes well but after version 1.1.0 release it got error then. The error log is placed below.

```javascript
[11:25:35] 'tpl' errored after 20 ms
[11:25:35] Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:317:21)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:327:19)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at isCompatibleEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:252:19)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:287:4)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at isCompatibleEngines (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:183:19)
    at isCompatibleEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:250:10)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:287:4)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
[11:25:35] 'build' errored after 27 ms
[11:25:35] Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:317:21)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:327:19)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:301:25)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at isCompatibleEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:252:19)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:287:4)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
    at new Errlop (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_errlop@4.1.0@errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/util.js:23:14)
    at isCompatibleEngines (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:183:19)
    at isCompatibleEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:250:10)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:287:4)
    at determineEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_editions@6.1.0@editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/webedit/.gitlab-runner/builds/c4180962/0/eris/20201013_h5_signinpic/node_modules/_istextorbinary@5.12.0@istextorbinary/index.cjs:4:38)
    at Module._compile (module.js:653:30)
```

**Comment by hzxulin** [comment]
I have also been facing this issue.

**Comment by lazd** [comment]
@hzxulin what version of node?

**Comment by lazd** [comment]
@jon2180 any idea why this would happen?

**Comment by hzxulin** [comment]
> @hzxulin what version of node?

node 8.12.0   npm 6.4.1

**Comment by lazd** [comment]
@mosquito1803 @hzxulin can you try node 10? Node.js 8.x Maintenance LTS cycle expired December 31, 2019 and is pretty out of date.

**Comment by hzxulin** [comment]
> @mosquito1803 @hzxulin can you try node 10? Node.js 8.x Maintenance LTS cycle expired December 31, 2019 and is pretty out of date.

@lazd But I need to use the Node 8 version for my project. Can I change the package version to 2.0.0

**Comment by lazd** [comment]
@mosquito1803 @hzxulin can you try adding:

```
dependencies: {
  "istextorbinary": "^4.0.0"
}
```

if that doesn't work, try 3.0, then 2.0. etc.

The package was upgraded because it has a vulnerability. It does not make sense to downgrade to an older version with a vulnerability to support a version of node that has reached end of life.

**Comment by mosquito1803** [comment]
@lazd Changing node version and `istextorbinary` package version may works but confused users like us, for npm will automatically install a new package upgrading the minor version. Just like what @hzxulin said, no support for specifed node version should better leading to a major version change of this package. Could you please release a 2.0.0 version instead?

**Comment by hzxulin** [comment]
> @mosquito1803 @hzxulin can you try adding the following to your `package.json`:
> 
> ```
> dependencies: {
>   "istextorbinary": "^4.0.0"
> }
> ```
> 
> if that doesn't work, try 3.0, then 2.0. etc.
> 
> ~The `istextorbinary` package was upgraded because it has a vulnerability. It does not make sense to downgrade to an older version with a vulnerability to support a version of node that has reached end of life.~ Its possible the package never suffered from a vulnerability and was simply upgraded with the rest of them. Looking into this.

@lazd This requires modification of our project package.json file. We have hundreds of such projects, and it is very difficult for me to do this

**Comment by lazd** [comment]
@hzxulin @mosquito1803 testing with 3.x now, it works on 8.0... Will release a patch if all goes well, but y'all need to update your node versions, 8.0 is EOL'd!

**Comment by lazd** [comment]
@hzxulin @mosquito1803 try `gulp-replace@1.1.1`

**Comment by hzxulin** [comment]
> @hzxulin @mosquito1803 try `gulp-replace@1.1.1`

@lazd    It worked. Thank you very much ! ❤

**Comment by lazd** [comment]
@hzxulin you're welcome! Thanks for reporting and sorry for the headaches caused. I added testing for node back to version 8 to avoid issues like this in the future.

I realize this is a widely used package and should support even the oldest node versions if possible, but still urge you to upgrade to a later version as soon as you can. If not for security, `async`/`await` and `import` are pretty cool too ;)

**Comment by mosquito1803** [comment]
> @hzxulin @mosquito1803 try `gulp-replace@1.1.1`

Thanks, it works here too!  Next time you want to abandon node 8, just help youself to update the package to 2.0.0.

**Comment by lazd** [comment]
@mosquito1803 TBH I had no idea node 8 would break because I wasn't testing on it, but now I am!

**Comment by mosquito1803** [comment]
> @mosquito1803 TBH I had no idea node 8 would break because I wasn't testing on it, but now I am!

It's true, node 8 should be out of date that we are using node 8 only in some old projects. Thanks again for your help!
