### ISSUE TITLE
Cannot find module 'istextorbinary'

### ISSUE THREAD

**Issue by silenceisgolden** [lazd/gulp-replace#33]
```
Gulp :: [14:47:21] Error: Cannot find module 'istextorbinary'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/AJ/dev/bz/insights-proj/apps/client-gulp-pdf/node_modules/gulp-replace/index.js:4:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by silenceisgolden** [comment]
seems to be error on latest release

**Comment by lazd** [comment]
Can you please try the following:

```shell
npm remove gulp-replace
npm install gulp-replace
```

And see if things work? There was a big problem with istextorbinary today and I had to release a version that used `istextorbinary@1.0.0`.

**Comment by silenceisgolden** [comment]
so in my package.json there was `^0.5.0`. Not sure why, but when I switched it to `^0.5.1` it worked fine. Anyway, closing this, thanks for the response.

**Comment by lazd** [comment]
What happened was you installed `gulp-replace@0.5.0` and it pulled down `istextorbinary@1.0.1`, which had no code in it.

When you re-installed `gulp-replace`, you ended up with version `gulp-replace@0.5.1` which hardcodes `istextorbinary@1.0.0` so life worked again. The changing of the version number in your `package.json` was just a coincidence, removing and re-installing the package would have fixed it regardless.

Cheers!
