### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by 0nix** [lazd/gulp-replace#75]
When gulp-replace is installed normally, incorporated into a task and called, the following error message is returned:

```
Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/repo/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_duplex.js:21:23)
```

**Comment by ejfrancis** [comment]
FWIW i just installed and used this today without issue 

* node v6.7
* npm v3.10.3
* OSX v10.11.6
* gulp-replace v0.5.4

**Comment by lazd** [comment]
@0nix closing this, but if you are still having the issue, please provide the version numbers of the related modules as well as an example of how you're using it in your task.
