### ISSUE TITLE
TypeError: file.isNull is not a function

### ISSUE THREAD

**Issue by mkoert** [lazd/gulp-replace#79]
/usr/local/lib/node_modules/gulp-replace/index.js:11
      if (file.isNull()) {
               ^

TypeError: file.isNull is not a function
    at Transform.transform [as _transform] (/usr/local/lib/node_modules/gulp-replace/index.js:11:16)
    at Transform._read (/usr/local/lib/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Transform._write (/usr/local/lib/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/local/lib/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/local/lib/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at queueData (/usr/local/lib/node_modules/gulp/node_modules/map-stream/index.js:43:21)

**Comment by lazd** [comment]
Sounds like you're [using an old version of gulp](http://stackoverflow.com/questions/27366098/gulp-object-file-has-no-method-isnull).

Try upgrading your `gulp` package.
