### ISSUE TITLE
throw new Error('not implemented');

### ISSUE THREAD

**Issue by latel** [lazd/gulp-replace#87]
/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_transform.js:159:9)
    at Transform._read (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Transform.Writable.write (/Users/kevin/workspace/wzq/webuild/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at write (/Users/kevin/workspace/wzq/webuild/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/kevin/workspace/wzq/webuild/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/kevin/workspace/wzq/webuild/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)

**Comment by latel** [comment]
KEVINNWANG-MB0:webuild kevin$ node -v
v6.10.0

**Comment by lazd** [comment]
There is no way I can diagnose this problem with a stack trace that doesn't even include this module.

**Comment by GregOriol** [comment]
Also having this issue since updating from 0.5.4 to 0.6.1 :
```
node_modules/readable-stream/lib/_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (node_modules/readable-stream/lib/_stream_transform.js:159:9)
    at Transform._read (node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Transform.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Transform.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
```

Don't know exactly what is causing the issue but clearly related to your module @lazd 

Code is:
```
gulp.task('task', ['task1', 'task2'], function () {
  return gulp.src('./build/static/*.html')
//    .pipe(replace('bar', 'foo'))
    .pipe(gulp.dest('./build/inlined/'));
});
```
If I comment the line with replace, no error. It I uncomment it, this error appears.

What else could I do/check to help on this?

**Comment by lazd** [comment]
@GregOriol all tests pass on Node v6.6.0, and it seems I have `readable-stream@2.3.3` installed. What version is installed for you?

@oleggromov WDYT?

**Comment by GregOriol** [comment]
Weeeeell, I have to say I don't know what the problem was or is, but I just upgraded again to 0.6.1 to test your feedback and... it works #wtf. We can close this I guess.

**Comment by lazd** [comment]
@GregOriol so what version were you using before?

**Comment by GregOriol** [comment]
I really don't know, the only difference in the versions is this:

```
diff --git a/package.json b/package.json
index 7d2a204..51ddbc5 100644
--- a/package.json
+++ b/package.json
@@ -12,7 +12,7 @@
     "gulp": "^3.9.0",
     "gulp-premailer": "^0.4.0",
     "gulp-rename": "^1.2.2",
-    "gulp-replace": "^0.5.0",
+    "gulp-replace": "^0.6.1",
     "gulp-ruby-sass": "^2.0.6",
     "gulp-shell": "^0.6.3",
     "rimraf": "^2.6.1"
diff --git a/package-lock.json b/package-lock.json
index 5aeb6fb..1c86a9b 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -874,9 +874,9 @@
       "dev": true
     },
     "gulp-replace": {
-      "version": "0.5.4",
-      "resolved": "https://registry.npmjs.org/gulp-replace/-/gulp-replace-0.5.4.tgz",
-      "integrity": "sha1-aaZ5FLvRPFYr/xT1BKQDeWqg2qk=",
+      "version": "0.6.1",
+      "resolved": "https://registry.npmjs.org/gulp-replace/-/gulp-replace-0.6.1.tgz",
+      "integrity": "sha1-Eb+Mj85TPjPi9qjy9DC5VboL4GY=",
       "dev": true,
       "requires": {
         "istextorbinary": "1.0.2",
```

**Comment by lazd** [comment]
@GregOriol well I'm glad to hear updating to 0.6.1 fixes the issue for you. Thanks for providing more information. I'll close this for now, and if it comes back, please do comment.

**Comment by ashnewport** [comment]
I just had this error and solved it a different way.

It seems as though an older version of `readable-stream` was already installed from existing packages and `npm i -D gulp-replace` didn't update the local dependency versions already installed in my project.

For me, running `npm i readable-stream@2.3.3 --no-save` solved the issue. Alternatively I suppose I could have done a clean install by removing the `node_modules` folder and running `npm install` to be sure.

Hope this helps anyone else looking in the future.
